name: PR Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: yarn install
        run: yarn install
      - name: yarn lint
        run: yarn lint
