name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: watanabe0055/watanabe-barber-shop@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          target: "cs,yml"
          language: 日本語
